// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Src.Context;

#nullable disable

namespace Pressao.Migrations
{
    [DbContext(typeof(PressaoContext))]
    [Migration("20221121230826_Correcao Nome Tabela")]
    partial class CorrecaoNomeTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Src.Domain.PressaoArterial", b =>
                {
                    b.Property<long>("PressaoArterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PressaoArterialDiastalica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PressaoArterialSistolica")
                        .HasColumnType("INTEGER");

                    b.HasKey("PressaoArterialId");

                    b.ToTable("MyProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
