// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Src.Context;

#nullable disable

namespace Pressao.Migrations
{
    [DbContext(typeof(PressaoContext))]
    [Migration("20221121230429_Primeira Migração")]
    partial class PrimeiraMigração
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Src.Domain.Pressao", b =>
                {
                    b.Property<long>("PressaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PressaoDiastalica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PressaoSistolica")
                        .HasColumnType("INTEGER");

                    b.HasKey("PressaoId");

                    b.ToTable("MyProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
